# Site settings
title: José SAYAGO
subtitle: Personal Blog
email: jose@wplatino.com
description: > # this means to ignore newlines until "baseurl:"
  All opinions expressed here are my own personal views, and do 
  not represent the views of any company or organisation with 
  which I may be affiliated.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: joseluis_sayago
github_username:  josesayago

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty